import type { Metadata } from "next";

import { PraiseFont, OutfitFont } from "./fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "The Website Builders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PraiseFont.variable} ${OutfitFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
