import type { Metadata } from "next";
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Cta from '@/components/landing/Cta'

import { fontAlt, fontBody, fontHeading } from "./fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "The Website Builders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontAlt.variable} 
        ${fontBody.variable} 
        ${fontHeading.variable} antialiased`}>
        <div>
          <Header />
          {children}
          <Cta />
          <Footer />
        </div>
      </body>
    </html>
  );
}
