CREATE TABLE "bridger-app_domains" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"projectId" uuid NOT NULL,
	"domain" text NOT NULL,
	"verified" boolean DEFAULT false,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bridger-app_pages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"projectId" uuid NOT NULL,
	"title" text,
	"slug" text NOT NULL,
	"isRootpagee" boolean DEFAULT false NOT NULL,
	"description" text,
	"published" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"content" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bridger-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bridger-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "bridger-app_projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"userId" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"published" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "bridger-app_domains" ADD CONSTRAINT "bridger-app_domains_projectId_bridger-app_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."bridger-app_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bridger-app_pages" ADD CONSTRAINT "bridger-app_pages_projectId_bridger-app_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."bridger-app_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "domain_idx" ON "bridger-app_domains" USING btree ("domain");--> statement-breakpoint
CREATE INDEX "pages_title_idx" ON "bridger-app_pages" USING btree ("title");--> statement-breakpoint
CREATE INDEX "name_idx" ON "bridger-app_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "project_name_idx" ON "bridger-app_projects" USING btree ("name");